use_gpu: True
device: 0
early_stop:
  patience: 5
seed: 12345
expname: unweighted_exp_4
federate:
  mode: standalone
  client_num: 100
  total_round_num: 50
  sample_client_rate: 0.6
  join_in_info: ['num_sample']
  save_to: exp/unweighted_exp_4/model
data:
  root: data/
  type: femnist
  splits: [0.6,0.2,0.2]
  batch_size: 10
  subsample: 0.05
  num_workers: 0
  transform: [['ToTensor'], ['Normalize', {'mean': [0.1307], 'std': [0.3081]}]]
model:
  type: convnet2
  hidden: 2048
  out_channels: 62
  dropout: 0.0
train:
  local_update_steps: 1
  batch_or_epoch: epoch
  optimizer:
    lr: 0.01
    weight_decay: 0.0
grad:
  grad_clip: 5.0
nbafl:
  use: True
  mu: 0.1
  epsilon: 6
  constant: 1
  w_clip: 0.1
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 10
  metrics: ['acc', 'correct', 'feature_importance_cv', 'clever']
